import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  IRAN_PROVINCES,
  canonicalCity,
  canonicalProvince,
  isValidResidence,
  normalizeLocation,
  searchCities,
} from '../src/domain/iranLocations';

/**
 * Server-side half of the residence feature («محل سکونت»): the API re-validates whatever the
 * sign-up form sent, so the directory must be complete and its folding rules must match the web
 * copy exactly. `apps/web/src/lib/iranLocations.ts` is generated by the same script
 * (tools/build-iran-locations.mjs) — the last test fails if the two files ever drift apart.
 */
describe('iran locations (residence validation)', () => {
  it('holds all provinces and their cities', () => {
    expect(IRAN_PROVINCES).toHaveLength(31);
    expect(searchCities('خراسان رضوی')).toContain('مشهد');
    expect(searchCities('یزد')).toContain('یزد');
    for (const province of IRAN_PROVINCES) {
      expect(province.cities.length).toBeGreaterThan(0);
      const keys = province.cities.map(normalizeLocation);
      expect(new Set(keys).size).toBe(keys.length);
    }
  });

  it('canonicalises the client spelling and rejects impossible pairs', () => {
    expect(canonicalProvince('سیستان وبلوچستان')).toBe('سیستان و بلوچستان');
    expect(canonicalProvince('اصفهان')).toBe('اصفهان');
    expect(canonicalProvince('تهران بزرگ')).toBeNull();
    expect(canonicalCity('خراسان رضوی', 'مشهد')).toBe('مشهد');
    expect(canonicalCity('تهران', 'مشهد')).toBeNull();
    expect(isValidResidence('تهران', 'تهران')).toBe(true);
    expect(isValidResidence('', '')).toBe(false);
  });

  it('keeps the web copy of the directory byte-identical', () => {
    const server = path.resolve(__dirname, '../src/domain/iranLocations.ts');
    const web = path.resolve(__dirname, '../../apps/web/src/lib/iranLocations.ts');
    expect(fs.existsSync(web)).toBe(true);
    // Both files are generated together; run: node tools/build-iran-locations.mjs
    expect(fs.readFileSync(web, 'utf8')).toBe(fs.readFileSync(server, 'utf8'));
  });
});
