// Generates docs/ASSET-MAPPING.md — the auditable table «file → brand/product → UI usage».
// usage: node scripts/report-assets.mjs
import fs from 'node:fs';
import path from 'node:path';
import { REPO_ROOT, loadCatalog } from './lib/catalog-source.mjs';

const c = loadCatalog();
const brandName = new Map(c.brands.map((b) => [b.id, b.name]));
const lines = [];
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|');

lines.push('# Asset mapping — logos & product images (generated)');
lines.push('');
lines.push(
  '> Generated by `node scripts/report-assets.mjs` from «لیست برندها و محصولات سیلانه سبز» + «لوگو برندها و تصاویر محصولات». Do not edit by hand.',
);
lines.push(
  '> Matching is deterministic: brand logo = basename of `لوگو` column; product image = basename of `لینک تصویر` column (fallback: single file prefixed with product code).',
);
lines.push('');
lines.push(
  `**Summary:** brands ${c.brands.length} (logo matched ${c.brands.filter((b) => b.logoFile).length}) • active products ${c.products.length} (image matched ${c.products.filter((p) => p.imageFile).length}) • unused logos ${c.unusedLogos.length} • unused images ${c.unusedImages.length}`,
);
lines.push('');
lines.push('## Brand logos');
lines.push('');
lines.push('| # | Logo file | Brand | brandId | Storage path | UI usage |');
lines.push('|---|---|---|---|---|---|');
for (const b of c.brands) {
  const ext = b.logoFile ? path.extname(b.logoFile) : '';
  lines.push(
    `| ${b.sortOrder} | ${esc(b.logoFile ?? '❌ none')} | ${esc(b.name)} | ${b.id} | brands/${b.id}/logo${ext} | BrandLogo: brand grid, package/product header, admin content tree, marketer package cards |`,
  );
}
lines.push('');
lines.push('## Product images');
lines.push('');
lines.push('| # | Image file | Brand | Product | productId | Storage path | UI usage |');
lines.push('|---|---|---|---|---|---|---|');
c.products.forEach((p, i) => {
  const ext = p.imageFile ? path.extname(p.imageFile) : '';
  lines.push(
    `| ${i + 1} | ${esc(p.imageFile ?? '❌ none')} | ${esc(brandName.get(p.brandId) ?? p.brandName)} | ${esc(p.name)} | ${p.id} | products/${p.id}/main${ext} | product card, product page header, package cover fallback, admin product list |`,
  );
});
lines.push('');
lines.push('## Unused logo files (no active brand in the catalog — needs client decision)');
lines.push('');
for (const f of c.unusedLogos) lines.push(`- ${f}`);
lines.push('');
lines.push(
  '## Unused product image files (no ACTIVE product — variants, hidden/removed brands, legacy demo)',
);
lines.push('');
for (const f of c.unusedImages) lines.push(`- ${f}`);
lines.push('');
fs.writeFileSync(path.join(REPO_ROOT, 'docs', 'ASSET-MAPPING.md'), lines.join('\n'));
console.info(`[report-assets] wrote docs/ASSET-MAPPING.md`);
